# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('click', models.IntegerField()),
                ('top', models.IntegerField(default=0)),
                ('isDelete', models.BooleanField()),
                ('reserve', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Classification')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Classification'),
        ),
    ]
