# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 15:08
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='reserve',
        ),
        migrations.AddField(
            model_name='articles',
            name='cover',
            field=models.ImageField(default='/media/article_images/cover_defaule.png', upload_to='article_images'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='click',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
